name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - master

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file
        run: |
          cat << EOF > .env
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}
          EOF

      - name: Flutter pub get
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: false
          working-directory: android

      - name: Install gems
        run: |
          rm -rf vendor/bundle
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3
        working-directory: android

      - name: Check installed gems
        run: |
          bundle list | grep faraday
        working-directory: android

      - name: Verify Faraday
        run: |
          bundle exec ruby -e "require 'faraday'; require 'faraday/net_http_persistent'; puts 'Faraday OK'"
        working-directory: android

      - name: Fastlane Version
        run: |
          bundle exec fastlane --version
        working-directory: android

      - name: Create Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
      - name: Verify env
        run: |
          echo "URL EXISTS: ${{ secrets.SUPABASE_URL != '' }}"
          echo "KEY EXISTS: ${{ secrets.SUPABASE_ANON_KEY != '' }}"
      - name: Build and Distribute App
        run: |
          bundle exec fastlane android dist
        working-directory: android