name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file
        run: |
          cat << EOF > .env
          SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}
          STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}
          EOF

      - name: Verify Secrets
        run: |
          echo "SUPABASE_URL: ${{ secrets.SUPABASE_URL != '' }}"
          echo "SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY != '' }}"
          echo "STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY != '' }}"
          echo "STRIPE_SECRET: ${{ secrets.STRIPE_SECRET != '' }}"
          echo "FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT != '' }}"

      - name: Flutter pub get
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: false
          working-directory: android

      - name: Install gems
        working-directory: android
        run: |
          rm -rf vendor/bundle
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Check installed gems
        working-directory: android
        run: |
          bundle list | grep faraday

      - name: Verify Faraday
        working-directory: android
        run: |
          bundle exec ruby -e "require 'faraday'; require 'faraday/net_http_persistent'; puts 'Faraday OK'"

      - name: Fastlane Version
        working-directory: android
        run: |
          bundle exec fastlane --version

      - name: Create Firebase Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json

      - name: Build and Distribute App
        working-directory: android
        run: |
          bundle exec fastlane android dist

      - name: Verify APK
        run: |
          echo "================ APK FILE ================"
          ls -lh build/app/outputs/flutter-apk/

          echo ""
          echo "============= APK SHA256 ============="
          sha256sum build/app/outputs/flutter-apk/app-user-release.apk